lecture3/hello/urls.py
from django.urls import path
from . import views
# . the current directory

urlpatterns = [
    # "" empty string, no additional args
    path("",views.index, name="index"),
    path("cristian",views.cristian, name="cristian"),
    path("cthulhu",views.cthulhu, name="cthulhu"),
    #url pattern using placeholders
    path("<str:name>",views.greet, name="greet"),

]

lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include("hello.urls")),
    path("newyear/", include("newyear.urls")),
    path("tasks/", include("tasks.urls")),
]

lecture3/newyear/urls.py
from django.urls import path
from . import views
# . the current directory

urlpatterns = [
    path("",views.index, name="index"),
    # "" empty string, no additional args
]

lecture3/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    # "" empty string, no additional args
    path("",views.index, name="index"),
    path("addtask", views.addTask, name="addtask")
]

lecture3/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def cristian(request):
    return HttpResponse("This is working, Cristian")

def cthulhu(request):
    return HttpResponse("Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn")

# greet using HttpResponse
"""
def greet(request, name):
#takes an additional arg: name
    return HttpResponse(f"Hello,{name.capitalize()}")
    #we are using a python method """
# greet using render
def greet(request, name):
    return render(request, "hello/greet.html",{
        "name": name.capitalize()
    })

lecture3/newyear/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear" : now.month == 1 and now.day == 1
    })

lecture3/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="priority", min_value=1, max_value=5, )

# Create your views here.

#Changed in order to create sessions
#tasks = [] This is a local variable displayed for everybody

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = [ ]
    return render(request, "tasks/index.html", {
        #"tasks": tasks  variable tasks no longer exists
        "tasks":request.session["tasks"]
    })

def addTask (request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            #tasks.append(task)
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/addtask.html",{
                "form": form
            })
    return render(request, "tasks/addtask.html", {
        "form": NewTaskForm()
    })

lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Greet Page</title>
  </head>
  <body>
    <h1>Hello, {{name}}</h1>
    <p>This was created in the greet.html file</p>
  </body>
</html>

lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Hello</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    <p>This was written in my index.html file inside my hello application.</p>
  </body>
</html>

lecture3/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Is it New Year's?</title>
    <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
  <body>
    {% if newyear %}
      <h1>YES</h1>
    {% else %}
      <h1>NO</h1>
    {% endif %}

    <p>This was written in my index.html file inside my newyear application.</p>
  </body>
</html>

lecture3/tasks/templates/tasks/addtask.html
{% extends "tasks/layout.html" %}
{% block body %}
<h1>Add Tasks</h1>
<form class="" action="{% url 'tasks:addtask' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" name="" value="Add Task">
</form>
<a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

lecture3/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}
{% block body %}
<h1>Tasks</h1>
<ul>
  {% for task in tasks %}
    <li>{{ task }}</li>
  {% empty%}
    <li>No tasks</li>
  {% endfor %}
</ul>
<a href="{% url 'tasks:addtask' %}">Add a New Task</a>
{% endblock %}

lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Tasks</title>
  </head>
  <body>
    {% block body %}
    {% endblock %}
  </body>
</html>